version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 194722434535.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started...
      - docker build -t sundhar-backend-repo .

  post_build:
    commands:
      - echo Pushing image...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)
      - docker tag sundhar-backend-repo:latest 194722434535.dkr.ecr.us-east-1.amazonaws.com/sundhar-backend-repo:$IMAGE_TAG
      - docker push 194722434535.dkr.ecr.us-east-1.amazonaws.com/sundhar-backend-repo:$IMAGE_TAG
      - printf '[{"name":"fastapi-container","imageUri":"%s"}]' 194722434535.dkr.ecr.us-east-1.amazonaws.com/sundhar-backend-repo:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
