version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 194722434535.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t sundhar-backend-repo .
      - docker tag sundhar-backend-repo:latest 194722434535.dkr.ecr.us-east-1.amazonaws.com/sundhar-backend-repo:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push 194722434535.dkr.ecr.us-east-1.amazonaws.com/sundhar-backend-repo:latest
